## Data collection

1. **Subject: what topic does the data cover, and what real-world context does it represent?**
- **Topic**: Thông tin chi tiết về các tựa game được phát hành trên nền tảng Steam tính đến tháng 3 năm 2025. Dữ liệu tập trung vào ba khía cạnh chính: chiến lược thương mại (mức giá, doanh thu ước tính, nền tảng hỗ trợ), cấu trúc sản phẩm (thể loại, khối lượng DLC, đa ngôn ngữ) và sự đón nhận của thị trường (điểm đánh giá từ chuyên gia và người chơi).
- **Real-world context**: 

2. **Source: platform and full URL, original author or organization, publication date.**
- **Platform**: Kaggle
- **Full URL**: https://www.kaggle.com/datasets/artermiloff/steam-games-dataset
- **Authors**: Artemiy Ermilov, Assol Kubaeva, Артем Поспелов, Arina Nevolina
- **Publication date**: March 13th, 2025 (16:49:14 GMT+7)

3. **License: which license applies, and are there restrictions or attribution requirements?**
- **License**: MIT - Cho phép thực hiện mọi thao tác với tập dữ liệu (sử dụng, sao chép, chỉnh sửa, gộp, phân phối, thương mại hóa)
- **Attribution requirement**: Đính kèm thông báo bản quyền (copyright notice) và bản sao giấy phép MIT trong dự án
- Tác giả của tập dữ liệu sẽ không cung cấp bất kỳ bảo hành nào và không chịu trách nhiệm pháp lý cho những sai sót hoặc vấn đề phát sinh trong quá trình sử dụng dữ liệu để phân tích.

4. **Collection method: how the data was collected (survey, sensors, administrative records, scraping…), from which population, over what period, and with what known limitations or biases.**
- **Nguyên văn**: "The raw full version of the dataset is the full output of the SteamGamesScraper parsing. It contains duplicate game entries as well as playtest & server versions of games. The cleaned version of the Steam games dataset does not contain any duplicate game entries nor playtest and server versions of games. It is obtained from the raw dataset by filtering for `AppID % 10 == 0` and removing any games that contain strings "playtest", "dedicated server", "test server"."
- **Dịch**: Phiên bản thô (raw) của tập dữ liệu là kết quả đầu ra đầy đủ từ quá trình phân tích của công cụ SteamGamesScraper. Phiên bản này bao gồm các mục trò chơi bị trùng lặp, cũng như các phiên bản thử nghiệm (playtest) và phiên bản máy chủ (server) của các trò chơi. Phiên bản đã qua xử lý (cleaned) của tập dữ liệu trò chơi trên Steam không chứa các mục trò chơi trùng lặp, cũng như không bao gồm các phiên bản thử nghiệm hay phiên bản máy chủ. Phiên bản này được tạo ra từ tập dữ liệu thô bằng cách lọc theo điều kiện `AppID % 10 == 0` và loại bỏ tất cả các trò chơi có chứa các chuỗi ký tự như "playtest", "dedicated server" hoặc "test server".

5. **Motivation: why your group chose this dataset.**

##  Data exploration

In [1]:
import pandas as pd

df = pd.read_csv("games_march2025_cleaned.csv")

1. **Overview**

In [2]:
print(df.shape)

(89618, 47)

- **Number of rows and columns**: 89618 hàng, 47 cột
- **What one row represents**: mỗi hàng đại diện cho một tựa game duy nhất có mặt trên nền tảng phân phối Steam. Mỗi tựa game này được xác định và phân biệt độc lập với nhau thông qua mã định danh hệ thống ở cột appid.

In [3]:
df.iloc[:, 0:16].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   appid                 89618 non-null  int64
 1   name                  89618 non-null  object
 2   release_date          89618 non-null  object
 3   required_age          89618 non-null  int64
 4   price                 89618 non-null  float64
 5   dlc_count             89618 non-null  int64
 6   detailed_description  89421 non-null  object
 7   about_the_game        89398 non-null  object
 8   short_description     89498 non-null  object
 9   reviews               10401 non-null  object
 10  header_image          89618 non-null  object
 11  website               41114 non-null  object
 12  support_url           44110 non-null  object
 13  support_email         78798 non-null  object
 14  windows               89618 non-null  bool
 15  mac                   89618 non-null  bool
dtypes: bool(2), float64(1), int64(3), object(10)
memory usage: 9.7+ MB

In [4]:
df.iloc[:, 16:31].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   linux                 89618 non-null  bool
 1   metacritic_score      89618 non-null  int64
 2   metacritic_url        3547 non-null   object
 3   achievements          89618 non-null  int64
 4   recommendations       89618 non-null  int64
 5   notes                 16643 non-null  object
 6   supported_languages   89618 non-null  object
 7   full_audio_languages  89618 non-null  object
 8   packages              89618 non-null  object
 9   developers            89618 non-null  object
 10  publishers            89618 non-null  object
 11  categories            89618 non-null  object
 12  genres                89618 non-null  object
 13  screenshots           89618 non-null  object
 14  movies                89618 non-null  object
dtypes: bool(1), int64(3), object(11)
memory usage: 9.7+ MB

In [5]:
df.iloc[:, 31:47].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_score                89618 non-null  int64
 1   score_rank                39 non-null     float64
 2   positive                  89618 non-null  int64
 3   negative                  89618 non-null  int64
 4   estimated_owners          89618 non-null  object
 5   average_playtime_forever  89618 non-null  int64
 6   average_playtime_2weeks   89618 non-null  int64
 7   median_playtime_forever   89618 non-null  int64
 8   median_playtime_2weeks    89618 non-null  int64
 9   discount                  89618 non-null  int64
 10  peak_ccu                  89618 non-null  int64
 11  tags                      89618 non-null  object
 12  pct_pos_total             89618 non-null  int64
 13  num_reviews_total         89618 non-null  int64
 14  pct_pos_recent            89618 non-null  int64
 15  num_reviews_recent        89618 non-null  int64
dtypes: float64(1), int64(13), object(2)
memory usage: 10.9+ MB

- **Meaning and data type of each column**:

| Tên cột | Ý nghĩa | Kiểu dữ liệu |
|---|---|---|
| `appid` | ID của app | `int64` |
| `name` | Tên game | `object` |
| `release_date` | Ngày phát hành | `object` |
| `required_age` | Độ tuổi yêu cầu để chơi | `int64` |
| `price` | Giá bán | `float64` |
| `dlc_count` | Số lượng Downloadable Content, tức số lượng gói nội dung mở rộng có thể tải thêm | `int64` |
| `detailed_description` | Mô tả chi tiết về trò chơi | `object` |
| `about_the_game` | Thông tin giới thiệu trò chơi | `object` |
| `short_description` | Mô tả ngắn về trò chơi | `object` |
| `reviews` | Các nhận xét/đánh giá của người dùng về trò chơi | `object` |
| `header_image` | Đường dẫn đến ảnh quảng bá của trò chơi | `object` |
| `website` | Đường dẫn trang web của trò chơi | `object` |
| `support_url` | Đường dẫn trang liên hệ hỗ trợ | `object` |
| `support_email` | Email hỗ trợ | `object` |
| `windows` | Hệ điều hành mà trò chơi hỗ trợ | `bool` |
| `mac` | Hệ điều hành mà trò chơi hỗ trợ | `bool` |
| `linux` | Hệ điều hành mà trò chơi hỗ trợ | `bool` |
| `metacritic_score` | Điểm số trung bình có trọng số từ các nhà phê bình uy tín do Metacritic tổng hợp | `int64` |
| `metacritic_url` | Đường dẫn đến trang Metacritic đánh giá trò chơi | `object` |
| `achievements` | Số thành tựu mà game đạt được | `int64` |
| `recommendations` | Số lượt game được đề xuất | `int64` |
| `notes` | Ghi chú, thường là khuyến cáo những yếu tố có thể không phù hợp mà trò chơi có | `object` |
| `supported_languages` | Các ngôn ngữ mà game hỗ trợ | `object` |
| `full_audio_languages` | Các ngôn ngữ có bản âm thanh đầy đủ | `object` |
| `packages` | Gói phần mềm bao gồm base game đi kèm DLC hoặc nhiều tựa game trong cùng series với giá rẻ hơn | `object` |
| `developers` | Các nhà phát triển | `object` |
| `publishers` | Các nhà phát hành | `object` |
| `categories` | Danh mục | `object` |
| `genres` | Thể loại | `object` |
| `screenshots` | Các đường dẫn đến ảnh chụp màn hình trò chơi | `object` |
| `movies` | Đường dẫn đến những video liên quan đến trò chơi | `object` |
| `user_score` | Điểm người dùng đánh giá | `int64` |
| `score_rank` | Xếp hạng điểm | `float64` |
| `positive` | Số người chơi bấm Yes, thể hiện sự hài lòng hoặc đánh giá tốt | `int64` |
| `negative` | Số người chơi bấm No, thể hiện sự thất vọng, chê bai hoặc game có nhiều lỗi | `int64` |
| `estimated_owners` | Số lượng người sở hữu trò chơi được ước tính | `object` |
| `average_playtime_forever` | Thời gian chơi trung bình kể từ lúc game ra mắt | `int64` |
| `average_playtime_2weeks` | Thời gian chơi trung bình trong vòng 2 tuần kể từ thời điểm dữ liệu được thu thập | `int64` |
| `median_playtime_forever` | Thời gian chơi trung vị kể từ lúc game ra mắt | `int64` |
| `median_playtime_2weeks` | Thời gian chơi trung vị trong vòng 2 tuần kể từ thời điểm dữ liệu được thu thập | `int64` |
| `discount` | Mức giảm giá so với giá gốc ban đầu | `int64` |
| `peak_ccu` | Số lượng người chơi cùng lúc cao nhất trong một khoảng thời gian nhất định | `int64` |
| `tags` | Các nhãn từ khóa mô tả nội dung, thể loại hoặc đặc điểm của trò chơi | `object` |
| `pct_pos_total` | Tỷ lệ phần trăm đánh giá tích cực trên tổng số đánh giá từ trước đến nay | `int64` |
| `num_reviews_total` | Tổng số lượng review trong suốt vòng đời sản phẩm | `int64` |
| `pct_pos_recent` | Phần trăm đánh giá tích cực gần đây | `int64` |
| `num_reviews_recent` | Tổng số lượng review gần đây | `int64` |

In [6]:
def check_zero_values(df):
    numeric_cols = df.select_dtypes(include="number").columns

    result = pd.DataFrame({
        "Số lượng giá trị 0": df[numeric_cols].eq(0).sum(),
        "Tỷ lệ giá trị 0 (%)": (
            df[numeric_cols].eq(0).mean() * 100
        ).round(2)
    })

    return result[result["Số lượng giá trị 0"] > 0]

check_zero_values(df)

                          Số lượng giá trị 0  Tỷ lệ giá trị 0 (%)
required_age                           88589                98.85
price                                  14160                15.80
dlc_count                              75388                84.12
metacritic_score                       86071                96.04
achievements                           41090                45.85
recommendations                        72881                81.32
user_score                             89579                99.96
positive                               19425                21.68
negative                               30396                33.92
average_playtime_forever               81608                91.06
average_playtime_2weeks                88901                99.20
median_playtime_forever                81608                91.06
median_playtime_2weeks                 88901                99.20
discount                               82164                91.68
peak_ccu                               70698                78.89
pct_pos_total                             18                 0.02
pct_pos_recent                             2                 0.00

- **Columns to drop**: detailed_description ,about_the_game, short_description,reviews, header_image, website, support_url, support_email, metacritic_url, notes, screenshots, movies, score_rank

| Tên cột | Lí do drop |
|---|---|
| `detailed_description` | **Value là text dài:** Không có nhiều ý nghĩa trong phân tích, không được dùng trong các câu hỏi và thường có thông tin trùng lặp hoặc có thể thay thế bằng cột khác |
| `about_the_game` | **Value là text dài:** Không có nhiều ý nghĩa trong phân tích, không được dùng trong các câu hỏi và thường có thông tin trùng lặp hoặc có thể thay thế bằng cột khác |
| `short_description` | **Value là text dài:** Không có nhiều ý nghĩa trong phân tích, không được dùng trong các câu hỏi và thường có thông tin trùng lặp hoặc có thể thay thế bằng cột khác |
| `reviews` | **Value là text dài:** Không có nhiều ý nghĩa trong phân tích, không được dùng trong các câu hỏi và thường có thông tin trùng lặp hoặc có thể thay thế bằng cột khác |
| `header_image` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `website` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `support_url` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `support_email` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `metacritic_score` | **Tỷ lệ giá trị 0 cao:** Có khả năng do thiếu thông tin nên giá trị null được đồng bộ thành 0. Các cột số khác có giá trị 0 thực tế và vẫn có ý nghĩa |
| `metacritic_url` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `notes` | **Value là text dài:** Không có nhiều ý nghĩa trong phân tích, không được dùng trong các câu hỏi và thường có thông tin trùng lặp hoặc có thể thay thế bằng cột khác |
| `screenshots` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `movies` | **Value là đường dẫn:** Không có giá trị trong việc phân tích hoặc xử lý dữ liệu |
| `user_score` | **Tỷ lệ giá trị 0 cao:** Có khả năng do thiếu thông tin nên giá trị null được đồng bộ thành 0 |
| `score_rank` | **Có nhiều giá trị rỗng:** Không có giá trị sử dụng cao trong quá trình phân tích |
| `average_playtime_2weeks` | **Tỷ lệ giá trị 0 cao:** Có khả năng do thiếu thông tin nên giá trị null được đồng bộ thành 0 |
| `median_playtime_2weeks` | **Tỷ lệ giá trị 0 cao:** Có khả năng do thiếu thông tin nên giá trị null được đồng bộ thành 0 |

- **Columns to convert**:

| Cột | Chuyển đổi | Mô tả/Lí do |
|---|---|---|
| `appid` | Chuyển từ kiểu số sang `string` | Đây là mã định danh của ứng dụng, không dùng để tính toán |
| `release_date` | Chuyển từ kiểu văn bản sang `date` | Thuận tiện cho việc phân tích theo thời gian |
| `full_audio_languages` | Chuyển sang `list` | Một trò chơi có thể có nhiều ngôn ngữ âm thanh |
| `packages` | Chuyển sang `list` | Một trò chơi có thể có nhiều gói sản phẩm |
| `developers` | Chuyển sang `list` | Một trò chơi có thể có nhiều nhà phát triển |
| `publishers` | Chuyển sang `list` | Một trò chơi có thể có nhiều nhà phát hành |
| `categories` | Chuyển sang `list` | Một trò chơi có thể thuộc nhiều danh mục |
| `genres` | Chuyển sang `list` | Một trò chơi có thể thuộc nhiều thể loại |
| `tags` | Chuyển sang `list` | Một trò chơi có thể có nhiều nhãn mô tả |
| `name` | Chuyển từ kiểu `object` sang `string` | Đây là dữ liệu văn bản, cần chuẩn hóa về kiểu chuỗi |
| `supported_languages` | Chuyển từ kiểu `object` sang `string` | Giữ thông tin ngôn ngữ dưới dạng chuỗi |
| `estimated_owners` | Chuyển từ kiểu `object` sang `string` | Giá trị là khoảng số lượng người sở hữu, không phải số cụ thể để tính toán |
| `windows`, `mac`, `linux` → `os` | Gộp thành cột `os` có kiểu `list` | Tập hợp các hệ điều hành mà trò chơi hỗ trợ vào một cột duy nhất |

- **Duplicated or empty rows**: Không có, vì bộ dữ liệu nhóm chọn là phiên bản đã được làm sạch một phần, đảm bảo không có empty hay duplicated row.

In [7]:
drop_cols = [
    "detailed_description",
    "about_the_game",
    "short_description",
    "reviews",
    "header_image",
    "website",
    "support_url",
    "support_email",
    "metacritic_score",
    "metacritic_url",
    "notes",
    "screenshots",
    "movies",
    "user_score",
    "score_rank",
    "average_playtime_2weeks",
    "median_playtime_2weeks"
]

df.drop(columns=drop_cols, inplace=True)

In [8]:
df["os"] = df[["windows", "mac", "linux"]].apply(
    lambda row: [
        name for name, supported in zip(
            ["Windows", "macOS", "Linux"], row
        ) if supported
    ],
    axis=1
)

df.drop(columns=["windows", "mac", "linux"], inplace=True)

In [13]:
from ast import literal_eval

# Chuyển appid và release_date
df["appid"] = df["appid"].astype("string")
df["release_date"] = pd.to_datetime(
    df["release_date"], errors="coerce"
).dt.date

# Các cột chuyển sang list
list_cols = [
    "full_audio_languages",
    "packages",
    "developers",
    "publishers",
    "categories",
    "genres",
    "tags"
]

def to_list(value):
    if isinstance(value, list):
        return value

    if value is None or (isinstance(value, float) and pd.isna(value)):
        return []

    try:
        value = literal_eval(value)

        if isinstance(value, dict):
            return list(value.keys())

        return value if isinstance(value, list) else []
    except:
        return []

df[list_cols] = df[list_cols].apply(
    lambda col: col.map(to_list)
)

string_cols = [
    "name",
    "supported_languages",
    "estimated_owners"
]

df[string_cols] = df[string_cols].astype("string")

2. **Categorical columns**

In [11]:
report = []

for col in df.columns:
    values = (
        df[col].explode()
        if df[col].apply(lambda x: isinstance(x, list)).any()
        else df[col]
    )

    counts = values.value_counts(dropna=False)

    report.append({
        "Column": col,
        "Number of distinct values": values.nunique(dropna=True),
        "Most frequent value": counts.index[0] if not counts.empty else None
    })

report = pd.DataFrame(report)

display(report)

,Column,Number of distinct values,Most frequent value
0,appid,89618,730
1,name,88899,Alone
2,release_date,4459,2024-10-31
3,required_age,16,0
4,price,616,0.0
5,dlc_count,102,0
6,achievements,433,0
7,recommendations,4640,0
8,supported_languages,14560,['English']
9,full_audio_languages,2882,[]
10,packages,75740,[]
11,developers,56478,[]
12,publishers,49798,[]
13,categories,7471,"['Single-player', 'Family Sharing']"
14,genres,2689,"['Casual', 'Indie']"
15,positive,5087,0
16,negative,2525,0
17,estimated_owners,15,0 - 20000
18,average_playtime_forever,1851,0
19,median_playtime_forever,1639,0
20,discount,86,0
21,peak_ccu,1180,0
22,tags,70420,[]
23,pct_pos_total,102,-1
24,num_reviews_total,5346,-1
25,pct_pos_recent,95,-1
26,num_reviews_recent,830,-1
27,os,3,Windows

- **Number of distinct values and the most frequent ones**:

| Tên cột | Số lượng giá trị khác nhau | Giá trị xuất hiện nhiều nhất |
|---|---:|---|
| `appid` | 89618 | `730` |
| `name` | 88899 | `Alone` |
| `release_date` | 4459 | `2024-10-31` |
| `required_age` | 16 | `0` |
| `price` | 616 | `0.0` |
| `dlc_count` | 102 | `0` |
| `achievements` | 433 | `0` |
| `recommendations` | 4640 | `0` |
| `supported_languages` | 14560 | `['English']` |
| `full_audio_languages` | 2882 | `[]` |
| `packages` | 75740 | `[]` |
| `developers` | 56478 | `[]` |
| `publishers` | 49798 | `[]` |
| `categories` | 7471 | `['Single-player', 'Family Sharing']` |
| `genres` | 2689 | `['Casual', 'Indie']` |
| `positive` | 5087 | `0` |
| `negative` | 2525 | `0` |
| `estimated_owners` | 15 | `0 - 20000` |
| `average_playtime_forever` | 1851 | `0` |
| `median_playtime_forever` | 1639 | `0` |
| `discount` | 86 | `0` |
| `peak_ccu` | 1180 | `0` |
| `tags` | 70420 | `[]` |
| `pct_pos_total` | 102 | `-1` |
| `num_reviews_total` | 5346 | `-1` |
| `pct_pos_recent` | 95 | `-1` |
| `num_reviews_recent` | 830 | `-1` |
| `os` | 3 | `Windows` |

In [12]:
balance_report = []

for col in df.columns:
    values = (
        df[col].explode()
        if df[col].apply(lambda x: isinstance(x, list)).any()
        else df[col]
    )

    counts = values.value_counts(dropna=False)

    balance_report.append({
        "Tên cột": col,
        "Số giá trị khác nhau": values.nunique(dropna=True),
        "Giá trị xuất hiện nhiều nhất": counts.index[0],
        "Số lượng lớn nhất": counts.iloc[0],
        "Tỷ lệ lớn nhất (%)": round(
            counts.iloc[0] / counts.sum() * 100, 2
        )
    })

balance_report = pd.DataFrame(balance_report)

display(balance_report)

,Tên cột,Số giá trị khác nhau,Giá trị xuất hiện nhiều nhất,Số lượng lớn nhất,Tỷ lệ lớn nhất (%)
0,appid,89618,730,1,0.00
1,name,88899,Alone,6,0.01
2,release_date,4459,2024-10-31,141,0.16
3,required_age,16,0,88589,98.85
4,price,616,0.0,14160,15.80
5,dlc_count,102,0,75388,84.12
6,achievements,433,0,41090,45.85
7,recommendations,4640,0,72881,81.32
8,supported_languages,14560,['English'],44652,49.82
9,full_audio_languages,2882,[],49823,55.59
10,packages,75740,[],13819,15.42
11,developers,56478,[],221,0.25
12,publishers,49798,[],547,0.61
13,categories,7471,"['Single-player', 'Family Sharing']",19088,21.30
14,genres,2689,"['Casual', 'Indie']",5099,5.69
15,positive,5087,0,19425,21.68
16,negative,2525,0,30396,33.92
17,estimated_owners,15,0 - 20000,59320,66.19
18,average_playtime_forever,1851,0,81608,91.06
19,median_playtime_forever,1639,0,81608,91.06
20,discount,86,0,82164,91.68
21,peak_ccu,1180,0,70698,78.89
22,tags,70420,[],16872,18.83
23,pct_pos_total,102,-1,36419,40.64
24,num_reviews_total,5346,-1,36419,40.64
25,pct_pos_recent,95,-1,82931,92.54
26,num_reviews_recent,830,-1,82931,92.54
27,os,3,Windows,89588,74.87

- **Balance**:

| Tên cột | Số giá trị khác nhau | Giá trị xuất hiện nhiều nhất | Số lượng lớn nhất | Tỷ lệ lớn nhất (%) |
|---|---:|---|---:|---:|
| `appid` | 89618 | `730` | 1 | 0.00 |
| `name` | 88899 | `Alone` | 6 | 0.01 |
| `release_date` | 4459 | `2024-10-31` | 141 | 0.16 |
| `required_age` | 16 | `0` | 88589 | 98.85 |
| `price` | 616 | `0.0` | 14160 | 15.80 |
| `dlc_count` | 102 | `0` | 75388 | 84.12 |
| `achievements` | 433 | `0` | 41090 | 45.85 |
| `recommendations` | 4640 | `0` | 72881 | 81.32 |
| `supported_languages` | 14560 | `['English']` | 44652 | 49.82 |
| `full_audio_languages` | 2882 | `[]` | 49823 | 55.59 |
| `packages` | 75740 | `[]` | 13819 | 15.42 |
| `developers` | 56478 | `[]` | 221 | 0.25 |
| `publishers` | 49798 | `[]` | 547 | 0.61 |
| `categories` | 7471 | `['Single-player', 'Family Sharing']` | 19088 | 21.30 |
| `genres` | 2689 | `['Casual', 'Indie']` | 5099 | 5.69 |
| `positive` | 5087 | `0` | 19425 | 21.68 |
| `negative` | 2525 | `0` | 30396 | 33.92 |
| `estimated_owners` | 15 | `0 - 20000` | 59320 | 66.19 |
| `average_playtime_forever` | 1851 | `0` | 81608 | 91.06 |
| `median_playtime_forever` | 1639 | `0` | 81608 | 91.06 |
| `discount` | 86 | `0` | 82164 | 91.68 |
| `peak_ccu` | 1180 | `0` | 70698 | 78.89 |
| `tags` | 70420 | `[]` | 16872 | 18.83 |
| `pct_pos_total` | 102 | `-1` | 36419 | 40.64 |
| `num_reviews_total` | 5346 | `-1` | 36419 | 40.64 |
| `pct_pos_recent` | 95 | `-1` | 82931 | 92.54 |
| `num_reviews_recent` | 830 | `-1` | 82931 | 92.54 |
| `os` | 3 | `Windows` | 89588 | 74.87 |

In [14]:
import re

check_cols = [
    "supported_languages",
    "full_audio_languages",
    "developers",
    "publishers",
    "categories",
    "genres",
    "tags",
    "os"
]

def normalize_label(value):
    return re.sub(r"[\W_]+", "", str(value).strip().lower())

inconsistent_report = []

for col in check_cols:
    values = (
        df[col].explode()
        if df[col].apply(lambda x: isinstance(x, list)).any()
        else df[col]
    )

    values = values.dropna().astype(str).str.strip()

    groups = values.groupby(values.map(normalize_label))

    for normalized, group in groups:
        variants = sorted(group.unique())

        if len(variants) > 1:
            inconsistent_report.append({
                "Tên cột": col,
                "Nhãn chuẩn hóa": normalized,
                "Các biến thể": variants
            })

inconsistent_report = pd.DataFrame(inconsistent_report)

display(inconsistent_report)

         Tên cột  Nhãn chuẩn hóa                                Các biến thể
0     developers                                          [-, ---, ;), ?, ∇]
1     developers  1stimpactcoltd  [1st-impact co.,Ltd., 1st-impact co.,ltd.]
2     developers        1upgames                      [1UP Games, 1UP games]
3     developers   21cduckscoltd   [21c.Ducks Co., Ltd., 21cDucks co., Ltd.]
4     developers        221games                       [221 Games, 221GAMES]
...          ...             ...                                         ...
1523  publishers    zhanghailong                [ZhangHaiLong, Zhanghailong]
1524  publishers         zkgames                    [Z & K Games, Z&K Games]
1525  publishers      樂磚joybrick                 [樂磚 Joy Brick, 樂磚Joy Brick]
1526  publishers        类人猿leiry                        [类人猿Leiry, 类人猿leiry]
1527  publishers             陈世杰                                 [陈 世杰, 陈世杰]

[1528 rows x 3 columns]

In [15]:
summary = inconsistent_report.groupby("Tên cột").agg(
    so_nhom=("Nhãn chuẩn hóa", "nunique"),
    so_bien_the=("Các biến thể", lambda x: sum(len(v) for v in x)),
    vi_du=("Các biến thể", lambda x: "; ".join(
        " / ".join(map(str, v)) for v in list(x)[:3]
    ))
).reset_index()

summary.columns = [
    "Tên cột",
    "Số nhóm không nhất quán",
    "Số biến thể",
    "Một số ví dụ"
]

print(f"Tổng số dòng chi tiết: {len(inconsistent_report)}")
display(summary)

Tổng số dòng chi tiết: 1528

,Tên cột,Số nhóm không nhất quán,Số biến thể,Một số ví dụ
0,developers,863,1782,"- / --- / ;) / ? / ∇; 1st-impact co.,Ltd. / 1s..."
1,publishers,665,1377,/ - / -- / --- / . / ... / ? / @ / ∇; 1st-imp...

In [16]:
inconsistent_report.to_csv(
    "inconsistent_labels_details.csv",
    index=False,
    encoding="utf-8-sig"
)

- **Inconsistent labels and typos**:

| Tên cột | Số nhóm không nhất quán | Số biến thể | Một số ví dụ |
|---|---:|---:|---|
| `developers` | 863 | 1782 | `- / --- / ;) / ? / ∇`; `1st-impact co.,Ltd. / 1st-impact co.,ltd.` |
| `publishers` | 665 | 1377 | `"" / - / -- / --- / . / ... / ? / @ / ∇`; `1st-impact co.,Ltd. / 1st-impact co.,ltd.` |

In [29]:
rare_cols = [
    "developers",
    "publishers",
    "categories",
    "genres",
    "tags",
    "os"
]

min_count = 180  # changable
rare_summary = []

for col in rare_cols:
    values = df[col].explode()
    counts = values.value_counts()

    rare = counts[counts < min_count]

    rare_summary.append({
        "Tên cột": col,
        "Ngưỡng min_count": min_count,
        "Số category ban đầu": len(counts),
        "Số category hiếm": len(rare),
        "Số category sau khi gom": len(counts) - len(rare) + 1,
        "Số lượt bị gom": rare.sum(),
        "Tỷ lệ bị gom (%)": round(
            rare.sum() / counts.sum() * 100, 2
        )
    })

rare_summary = pd.DataFrame(rare_summary)

display(rare_summary)

,Tên cột,Ngưỡng min_count,Số category ban đầu,Số category hiếm,Số category sau khi gom,Số lượt bị gom,Tỷ lệ bị gom (%)
0,developers,180,11,9,3,1088,1.22
1,publishers,180,35,30,6,3747,4.19
2,categories,180,36,0,37,0,0.00
3,genres,180,24,1,24,149,0.06
4,tags,180,391,32,360,4327,0.43
5,os,180,3,0,4,0,0.00

- **Rare categories that should be grouped**: Tạm cho rằng giá trị có tỉ lệ xuất hiện dưới 0.2% (tương đương xuất hiện dưới 180 lần) là rare, tỉ lệ này (hay giá trị `min_count`) có thể được thay đổi tùy vào:
    - Mục đích phân tích hoặc xây dựng mô hình
    - Số lượng category hiện có
    - Tỷ lệ dữ liệu bị gom vào "Other"
    - Ý nghĩa thực tế của category đó

    Tuy nhiên, không nên gom các category hiếm nhưng có ý nghĩa rõ ràng.

    | Tên cột | Số category ban đầu | Số category hiếm | Số category sau khi gom | Số lượt bị gom | Tỷ lệ bị gom (%) |
    |---|---:|---:|---:|---:|---:|
    | `developers` | 11 | 9 | 3 | 1088 | 1.22 |
    | `publishers` | 35 | 30 | 6 | 3747 | 4.19 |
    | `categories` | 36 | 0 | 37 | 0 | 0.00 |
    | `genres` | 24 | 1 | 24 | 149 | 0.06 |
    | `tags` | 391 | 32 | 360 | 4327 | 0.43 |
    | `os` | 3 | 0 | 4 | 0 | 0.00 |

In [ ]:
'''
Xóa comment và chạy code bên dưới để xuất CSV mới, xóa cell này nếu không cần thiết.

df.to_csv("steam_games_mar2025.csv")
'''